name: Auto Run Python to Google Sheets

on:
  schedule:
    # 9h15, 10h15, 11h15, 13h15 giờ VN (UTC +7)
    - cron: "15 2,3,4,6 * * *"
  workflow_dispatch:

jobs:
  run-job:
    runs-on: ubuntu-latest

    steps:
      # 1. Lấy code từ repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 3. Tạo file credentials từ GitHub Secrets
      - name: Create Google credentials
        run: |
          echo '${{ secrets.GOOGLE_CREDENTIALS }}' > creds.json

      # 4. Tạo venv + cài thư viện
      - name: Setup venv & install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 5. Run script
      - name: Run main script
        run: |
          source venv/bin/activate
          python main.py
